config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to @flat, notice: 'Flat was successfully edited.'
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to @flat, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit "Create Flat", class: "btn btn-primary"%>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit Flat</h1>

<%= render "form", flat: @flat %>

<%= link_to "Back to all flats", flats_path %>

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.length %>)</h1>
<div class="container">
  <ul>
    <% @flats.each do |flat| %>
      <li><div class="card">
        <h4><%= flat.name %></h4>
        <p><%= flat.description %></p>
        <p><i class="fa-solid fa-user-group"></i> <%= flat.number_of_guests %></p>
        <p><i class="fa-solid fa-dollar-sign"></i> <%= flat.price_per_night %></p>
        <div class="card-footer">
          <%= link_to "More info", flat_path(flat), class: "link-primary" %>
          <%= link_to "Edit", edit_flat_path(flat), class: "link-warning" %>
          <%= link_to "Remove", flat_path(flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link-danger" %>
        </div>
      </div></li>
    <% end %>
  </ul>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render "form", flat: @flat %>

<%= link_to "Back to all flats", flats_path %>

app/views/flats/show.html.erb
<div class="title">
  <h1><%= @flat.name %></h1>
  <p><%= @flat.address %></p>
</div>
<div class="description">
  <h3>Description</h3>
  <p><%= @flat.description %></p>
</div>
<div class="book">
</div>
<div class="details">
  <h3>Details</h3>
  <p><%= @flat.number_of_guests %></p>
  <p>$<%= @flat.price_per_night %></p>
</div>
<%= link_to "Edit", edit_flat_path(@flat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <nav>
      <%= link_to "fAirbnb", flats_path %>
      <%= link_to "Add Flat", new_flat_path , class: "btn btn-primary" %>
    </nav>
    <%= yield %>
  </body>
</html>